### ISSUE TITLE
Create a database

### ISSUE THREAD

**Issue by Daniel17sep** [russleyshaw/Colisee#1]
Create a database that can store:
1. Client (player) objects
      -Name (text field)
      -Git hash (text field)
      -Tag (text field)
      -Rating/Eloe (int or float)
      -Language
      -Embargoed (temp-banned) - Client does something bad, not allowed to play until they push new code (bool)
      -Embargo reason - reason why they were embargoed (text field)
      -Eligible - whether or not a team is eligible to compete for prizes - this info comes from the webserver
      -Any other needed fields
2. Game objects
      -Clients in game
      -Winner(s)
      -Win reasons(s) (text field)
      -Loser(s)
      -Lose reason(s) (text field)
      -Status (Completed, Failed, Running, etc.)
      -Gamelog location - location of the gamelog, if local a directory or if cloud based a URL
      -Any other needed fields
3. Match objects (for tournaments)
      -Games in match
      -Winner(s)
      -Losers(s)
      -Status
      -Any other needed fields
4. Any other needed objects

Misc. info that will need to be stored however you like:
-Game slug (denotes the game name, received from webserver and will need to be passed to the clients during start
-Mode - What game is being played, where the webserver is, testing or actual running mode, where gamelogs and build output data is sent, etc.

Other requirements:
1. Method to easily modify database contents manually
2. Relatively quick - Likely almost every part of Colisee will interface with the database, so it should be fast. One of the biggest speed limitations of the current arena is it's database.
3. Database fields and objects should be modifiable without dumping the database

Final notes:
-If I didn't specify the type or give examples of contents of a field then you are free to make it what you wish, just keep in mind webserver compatibility
-If you look (and you probably should) at the current arena's database, keep in mind that it's majorly bloated with fields that aren't used anymore.
-I may add requirements if I find I've forgotten any

Mainly related to #4 and #23 - @russleyshaw

**Comment by russleyshaw** [comment]
What is the purpose of the database? (Remember, there are non-siggame devs in here, so when you add requirements, dont forget to add a bit of a WHY part) @Daniel17sep

**Comment by Daniel17sep** [comment]
Umm ok (sorry not a professor here). We need a database so we can keep track of everything that goes on.  All of these results and records need to exist so competitors can see how they're doing, and so if something goes wrong we at least have a chance of knowing where and how.

**Comment by russleyshaw** [comment]
why not just store those variables within the running "arena" process?

**Comment by Daniel17sep** [comment]
That's A LOT of data to store runtime.  Also, and more importantly, if the arena is taken down completely (whether intentionally or not), that data needs to be kept.

**Comment by Daniel17sep** [comment]
It's also difficult to centralize data for use all over if it's not in a database.

**Comment by tjk43b** [comment]
IFF we are going to need a database, I'll go ahead and assign myself for this task, as I already have XAMPP installed on my laptop, and very recently took CS2300, which is what I think is Database Systems.

**Comment by russleyshaw** [comment]
We are using express in node js, not campo stack

**Comment by russleyshaw** [comment]
I am not completely sure what the database is going to contain just yet. We will need an idea for a schema and stuff. Remember, we are using NodeJS, which means you will probably need to find some sort of Javascript binding to whatever database we use. We will most likely be using Postgres as previous arena used it

**Comment by russleyshaw** [comment]
Mainly related to #4 and #23 
In the past PostGres SQL was used.

**Comment by russleyshaw** [comment]
init.sql is created and with docker, postgresql installation is easy. I highly recommend using pgadmin3 to manually interact with it. 

More issues will be made as we discover features that are lacking
