### ISSUE TITLE
Random Scheduler queuing on database

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#104]
Creating the games on the database in a `scheduled` status, then transitioning that status to `playing` when a play server actually plays that scheduled match would be better than storing the schedule queue in memory.

The matches are eventually added to the database anyways so there is no space saved by queueing in memory. It also allows SQL query access to the next game.

The next match could be determined by doing   
```UPDATE match SET status = "sending" WHERE id = (SELECT id FROM match WHERE status="scheduled" ORDER BY scheduled_time LIMIT 1) RETURNING *```  
when a next game is requested. Then, once the player receives the match  
```UPDATE match SET status = "playing" WHERE id = ID RETURNING *```  
is ran to transition the game out of a sending mode into playing mode. The sending mode is so that a game can be taken completely out of the scheduled pool when a new game is requested.

**Comment by grwqk6** [comment]
Added Match.create() to Scheduler.scheduleOnce() and took match_queue[] out.

**Comment by russleyshaw** [comment]
@grwqk6 Status? Is this working properly?

**Comment by russleyshaw** [comment]
Does it?
