### ISSUE TITLE
Make random scheduler select only building clients

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#107]
Currently the scheduler choses any client randomly. Instead, it should be updated to select only building clients.

This will probably involve moving the getRandom SQL query into the random scheduler so you can update it with a few conditions. The main condition to check is if `build_success` is `true`, that means that the client has been built.

**Comment by grwqk6** [comment]
I have to put this in the Client.getRandom() query since that is what the RandomSchedulerType calls in its genNext() to get the client.Ids for the match.

**Comment by russleyshaw** [comment]
@grwqk6 this functionality is finished I think.

Make sure to comment on issues to let me know the progress
