### ISSUE TITLE
Number of clients config parameter

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#132]
Each game can have N number of clients playing a single match. this number should be added to the config.

For now, make the value `2`

**Comment by russleyshaw** [comment]
new web server is going to have `min_teams` and `max_teams` as options for a given MMAI tournament. This functionality for now can just be replicated in the config default/config.json

```
"min_players": 2,
"max_players": 2,
```

**Comment by grwqk6** [comment]
Done.
