### ISSUE TITLE
Colisee Requests from webserver

### ISSUE THREAD

**Issue by Daniel17sep** [russleyshaw/Colisee#14]
-Client object (name, git hash, tag, eligible, repo, language)

**Comment by russleyshaw** [comment]
What identifying info would the Arena give to the web server to get the ClientObject it requested?

Like a client ID?

**Comment by Daniel17sep** [comment]
We get a username and password from the webserver.  That allows us to pull the client's information.  Part of that information the repo name, which it technically a secret.  Having that repo name is considered permission to clone clients.

**Comment by russleyshaw** [comment]
So what does the HTTP request look like then? I need more specifics on the network communication.

 I need to know what the requests are and the schema to expect back

**Comment by Daniel17sep** [comment]
In Python:
```api_url = api_url_template + game_name
r = requests.get(api_url, auth=(WEBSITE_USER_NAME, WEBSITE_ARENA_PASSWORD), verify=False)```
The webserver returns a JSON object containing all the clients.  See https://github.com/siggame/octo-robot/blob/master/masterblaster/utilities/webinteraction.py in the current arena to see what all it gets.

**Comment by Daniel17sep** [comment]
I found this laying around my files, here you go!
[Example Webserver JSON.txt](https://github.com/russleyshaw/Colisee/files/450576/Example.Webserver.JSON.txt)
