### ISSUE TITLE
Button Visibility

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#143]
It is very difficult to view where the button begins and ends.

Probably change the color slightly from the standard panel color

![image](https://cloud.githubusercontent.com/assets/2314816/20826422/58586b22-b830-11e6-8852-2bebf317424f.png)

**Comment by minhquan2106** [comment]
@russleyshaw can you please tell me how I pull up this webpage? I modified the css file and tried to run the servers, but I could not run this page to test.

**Comment by minhquan2106** [comment]
ok, got it localhost:5401 :)
