### ISSUE TITLE
Create Schedulers

### ISSUE THREAD

**Issue by Daniel17sep** [russleyshaw/Colisee#2]
Create game schedulers.  These will create games to be played.

Required schedulers:
1. Competition Scheduler
      -Runs during the entire competition (except during the tournament and quickdraws).  Games scheduled by this scheduler are what the competitors will use to test their clients.
      -Should generally put clients of similar skill (based on how they've been doing) up against each other.  This measure of skill should be able to change quickly, that way if a team comes up with a much better strategy, they are put up against better teams quickly and not getting meaningless wins for 3 hours.  See https://github.com/siggame/octo-robot/blob/master/masterblaster/scheduler_window_swiss.py in the current arena for one way of doing this.
2. Quickdraw/Tournament Scheduler(s)
      -Runs the quickdraws (mini-tournaments) and the tournament
      -Runs "matches", which are 7 games and the winner is 4/7.  Should run all 7 games at the same time, we do not have time to wait and see if all 7 games are necessary (eg. if player wins first 4 games)
      -In the current arena, both are handled by the same scheduler, but that is NOT a requirement
      -Should log data with the database so if it crashes or someone stops it the quickdraws/tournament can be resumed when it is started again without starting over.
      -If you want to look at what we use now, see https://github.com/siggame/octo-robot/blob/master/masterblaster/scheduler_tournament.py in the current arena.
      -We currently use Single Elimination style for quickdraws and Triple Elimination style for tournaments.  If you would like to use some different style, ask me first.
      -In the current arena, the quickdraws/tournament have to be "built" before the scheduler can run, this is optional.  See https://github.com/siggame/octo-robot/blob/master/masterblaster/autobuild_quickdraw.py and https://github.com/siggame/octo-robot/blob/master/masterblaster/autobuild_tournament.py in the current arena.
3. Validating Scheduler
      -Runs every client to see if they break
      -Is it's own separate scheduler in the current arena, but it could be part of the quickdraw/tournament scheduler(s) if you wish.

Other requirements:
-Common game scheduler.  The schedulers discussed above determine HOW games should be scheduled, but should call on this to actually schedule a game.  The purpose of this is to make it easier to A. make it so a change down the road in how games are scheduled is much easier to make and B. To make writing of new schedulers down the road easier.  See https://github.com/siggame/octo-robot/blob/master/arena/thunderdome/sked.py in the current arena.
-All schedulers should be able to schedule very quickly. So far we've run up to 100 games at once, and as cloud computing becomes cheaper and MegaMinerAI gets bigger, we will likely run more than that.

Final Notes:
-If you look (and you probably should) at the current arena's schedulers, keep in mind that many of them are last minute hack togethers, have endured years of "lazy fixes", and/or are not working/complete at all.
-I may add requirements if I find I've forgotten any.

**Comment by russleyshaw** [comment]
@Daniel17sep you say to look at code in the current arena, but the current arena is closed source

**Comment by Daniel17sep** [comment]
@russleyshaw I need a list all Github accounts to be given access to view current arena source.

**Comment by Daniel17sep** [comment]
**Optional** cool thing to add: Play less games with clients that haven't updated their code in a while (# of gamewise)

**Comment by russleyshaw** [comment]
An initial scheduler needs to be developed for future development on Play servers #3 
For now, a scheduler could constantly put 2 random clients on an internal queue. An API, when accessed could pull them off the queue

`GET /api/v2/sched/next `

A list of clients does not exist, but could be easily added as a list of strings to the head server for now

**Comment by grwqk6** [comment]
I think implementing two separate lists of clients by ranking(r0 -r1) will be enough to test schedulers. the way i read the code is ranking is just by score of the game. We can than use this score to find the clients their opponents within the same list. I have read a lot of the code so far and it reads not so pretty( my ability to read python is not as good as it once was) but is readable. I will make sure to comment the code heavy so you can follow.

**Comment by russleyshaw** [comment]
@grwqk6 Your first task is to randomly pairing clients. You do not care about ranking.

1) get 2 "clients" (will later be calls to a database)
2) push the clients into the queue

**Comment by russleyshaw** [comment]
The Scheduler class might look something like

```
class BaseSchedulerType {
    virtual onStart();
    virtual onStop();
    virtual onPause();
   virtual onPlay();
}

//Psuedocode
class Scheduler
private:
    SchedulerType currentSchedulerType; //Tournament, Random, etc.
    Queue<[Client1, Client2]> schedule;

public:
    void start();
    bool started();
    void stop();
    bool stopped();
   void pause();
   bool paused();
   void play();
   bool playing();

   void switchTo(SchedulerType newSchedulerType);

   void inject([Client1, Client2, ...]);

   void next(); //Dequeues game off schedule queue
   

```

**Comment by russleyshaw** [comment]
Closing for now, more specific issues to come
