### ISSUE TITLE
Turn mock services & colisee server's ports and URIs into config

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#22]
Un-hardcode any ports and server locations and turn them into NPM configuration options

https://docs.npmjs.com/misc/config#per-package-config-settings

head http://localhost:3000
build http://localhost:3001
play http://localhost:3002 ----- NOTE THERE WILL BE MULTIPLE POTENTIAL PLAY SERVERS
mock vis http://localhost:3003
mock web http://localhost:3003
etc...

**Comment by russleyshaw** [comment]
using `config` package in npm that reads `config/default.json` Ties nicely with handlebars which is able to embed the URL and ports into the served HTML pages

**Comment by grwqk6** [comment]
I will push this once I have Ubuntu and other services running on my computer tomorrow. I have it already written up . and is changing the ports and URIs (URLs) nicely from terminal.
