### ISSUE TITLE
Google Cloud or AWS?

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#24]

**Comment by Daniel17sep** [comment]
Both? The goal was to make so it wasn't dependent on anything, making it so it could run on either or anywhere else for that matter.  That said, code has to be written to make it compatible with either cloud service (eg. starting play servers on AWS is a different process than starting them on Google Cloud).  I guess what I'm saying is to condense the cloud service specific code into as few functions/modules as possible, hopefully making it easier to switch out that code later so it can run wherever we want it to.  Plan on that architecture for now and I will determine which we plan on using in the near future.  Once we know that you guys can set it up for that one.

**Comment by Daniel17sep** [comment]
Google Cloud is WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY cheaper, throw any inklings of using Amazon away and set us up for Google!

**Comment by russleyshaw** [comment]
How much cheaper?

**Comment by Daniel17sep** [comment]
2x or better depending on usage.

**Comment by russleyshaw** [comment]
oh wow
