### ISSUE TITLE
Create Build Server

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#26]

**Comment by russleyshaw** [comment]
Current status is working communication between web server and build server for when web server requests build to be updated. Researching and implementing docker images for individual build clients such as CPP, java, c# so that the images can be cloned and have the git repos put inside them

**Comment by Daniel17sep** [comment]
There should be a way to change the dependencies in a client language's docker image during the competition, in case we need to change a version or add something we forgot.

**Comment by russleyshaw** [comment]
we would just need to update individual dockerfiles on the build_server

**Comment by russleyshaw** [comment]
Merged in, closing in preference of smaller issues
