### ISSUE TITLE
Request authentication

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#41]
Messages like "Player 1 won" will be sent between servers and without some form of authentication, it would be impossible to tell if someone happened upon the IP address of the head_server or any other components and made a phony request. This is half question, half feature, half bug, as I dont know if there is a need for any more secure measures, or if so, how they would be implemented

**Comment by Daniel17sep** [comment]
Doesn't need to be complicated. Idea: generate a random number, send it as part of the game job, then send it back with game update, compare

**Comment by russleyshaw** [comment]
Something i was thinking of was just to make sure that the request came from whatever is defined in its config. I.e, the head server shouldnt be told a player won from anyone except the play servers, which would be defined already.
