### ISSUE TITLE
Add other client language base images

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#43]
C++ is the only docker base image being generated at startup right now.

Support needs to be added for the remaining languages (csharp, java, python, javascript)

**Comment by Daniel17sep** [comment]
See the joueur.x and octo-robot repo readmes for full lists of required dependencies.

**Comment by Daniel17sep** [comment]
If a client is "Human", it should be built as javascript.  This is because our human playable chess client is written in javascript.

**Comment by russleyshaw** [comment]
Javascript has been added, but not tested. Softly blocked until better test git repos are created
