### ISSUE TITLE
Create central error/message service

### ISSUE THREAD

**Issue by Daniel17sep** [russleyshaw/Colisee#6]
Create something that would allow any part of the arena (head node and workers) to send messages (mostly errors) back to the monitoring site and display them on an error/message page.  This service should be able send emails to predefined address for critical errors.

**Comment by russleyshaw** [comment]
What about a database of messages and errors?

**Comment by Daniel17sep** [comment]
I don't know if we really need to keep them, it's mostly a warning to a human that things blew up, and hopefully tells what and how and why.

**Comment by russleyshaw** [comment]
What database was used before? Django's?

**Comment by Daniel17sep** [comment]
Errors and messages are not logged at all in the current arena.

**Comment by Daniel17sep** [comment]
If you're talking about the master database, the current arena uses a postgres database (which is quite good) with Django to access it (which is quite bad b/c Django is slow AF)

**Comment by russleyshaw** [comment]
We may stick with Postgres. I've used it before and I liked it. If for some reason we want to go with a nosql database, ive used MongoDB before, but SQL i think is fine for us

**Comment by russleyshaw** [comment]
See #4 to combine the two. an "error" is just a log with an "error" severity level

**Comment by Daniel17sep** [comment]
You're right, and as long as the logger posts the error somewhere where an arena dev will see it, the two can definitely be merged.
