### ISSUE TITLE
Improved Scheduler Functionality

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/Colisee#98]
- [x] starting scheduler should first clear queue
- [x] starting scheduler should create a new tournament in database (new tournament db should be created) (stub this out for now until we get an actual Tournament Interface
- [x] should not schedule if beyond max scheduled games

**Comment by mmillerick** [comment]
Since queue is on the database now instead of RAM, clearing is no longer applicable.

**Comment by grwqk6** [comment]
Added check MAX_SCHEDULED check to Scheduler.start().
Added a schedule in Db table "schedule" with status="stopped" after  MAX_SCHEDULED check in Scheduler.start()

**Comment by russleyshaw** [comment]
One thing to note is that since the checking of the number scheduled and scheduling isnt an atomic operation, its possible to go over the MAX_SCHEDULED. This is okay and we may eventually devise a way to force schedule games for tournaments and things

If your branch is ready, create a pull request.
